name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  super-linter:
    name: Super-Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@c05768164eed53bac7c82aade7a14a76955206d4962cd41be97118db96fa5996
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_YAML: true

  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    needs: super-linter

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@9a7437ba3baa2c38b53eae62ac524250574c9e71f4ced0148542d65f823aeaef
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    needs: gitleaks

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          fetch-depth: 0

      - name: Install Semgrep
        run: pipx install semgrep

      - name: Run Semgrep
        run: semgrep scan --config auto --error